### ISSUE TITLE
Partition 2 support for rankings and possibly reports?

### ISSUE THREAD

**Issue by shinklja** [gngrninja/NinjaBotCore#16]
Currently, the discord bot pulls the rankings from the 1st partition in warcraftlogs for ToS, but unfortunately that isn't the current patch.  

I wasn't quite sure how to implement this as I am not so versed in the warcaftlogs api. However, I didn't see anything that got the latest partition and it seemed to me that the partitions had to be manually handled. I could be completely wrong because like I said I don't know warcraftlogs api that well.

Personally, I was thinking maybe it could be handled as something we could pass in "7.3" = 2 and "7.2.5" =1 for ToS zone and if not expressly passed in that the code would take the highest value in the list for that encounter.

I wasn't sure how to message you on here, but if you have any questions @Fiolated#9828  is my discord.

Thanks!

**Comment by gngrninja** [comment]
Hey there! Thanks for the heads up. I added partition 2 support in the latest build. The bot has been restarted, and it should now function properly. 

I found this tidbit from their documentation:

> The partition group to query for. Most zones have only one partition, and this can be omitted. Hellfire Citadel has two partitions (1 for original, 2 for pre-patch). Highmaul and BRF have two partitions (1 for US/EU, 2 for Asia).

Let me know if there's anything else I can add that you'd like, or if you have any feedback.
